monolog:
  channels: ['elenyum_controller_stats']
  handlers:
    elenyum_controller_stats:
      type: stream
      path: '%kernel.logs_dir%/elenyum/controller_stats.log'
      level: info
      channels: ["elenyum_controller_stats"]
